# 删除 version 字段（兼容 Docker Compose V2）
services:
  super-tictactoe:
    # 显式指定镜像名，避免 Docker 默认生成随机名称
    image: super-tictactoe:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: super-tictactoe
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    restart: always
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true  # 确保该网络已存在（由 1Panel 创建）