# 删除 version 字段（兼容 Docker Compose V2）
services:
  super-tictactoe:
    # 直接使用 build 构建，不再指定 image 字段（避免拉取远程镜像）
    build:
      context: .
      dockerfile: Dockerfile
    container_name: super-tictactoe
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    restart: always
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true