# 删除 version 字段（兼容 Docker Compose V2）
services:
  super-tictactoe:
    image: super-tictactoe:1.0.0  # 添加镜像名称
    build:
      context: .
      dockerfile: Dockerfile
    container_name: super-tictactoe
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    restart: always
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true