version: '3'
services:
  super-ttt:
    build:
      context: https://github.com/qxdho/super-tic-tac-toe.git#main
      dockerfile: Dockerfile
    container_name: super-ttt
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      - DEPLOY_PASSWORD=${DEPLOY_PASSWORD}
      - PLAYER_LIMIT=${PLAYER_LIMIT}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true