# 直接删除 version 字段（Docker Compose V2 不需要）
services:
  super-tictactoe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true